[variables]
    COMPOSER_ALLOW_SUPERUSER = '1'
    APP_ENV = 'production'
    APP_DEBUG = 'false'
    LOG_CHANNEL = 'stderr'
    NIXPACKS_NODE_VERSION = '24'

[phases.setup]
    nixpkgsArchive = '549bd84d6279f9852cae6225e372cc67fb91a4c1'
    nixPkgs = ['php83', 'php83Packages.composer', 'nodejs_24', 'mariadb.client', 'pkg-config', 'libxml2', 'zlib', 'libzip', 'icu']

[phases.install]
    cmds = ['composer install --no-interaction --optimize-autoloader --no-dev --ignore-platform-reqs']

[phases.build]
    cmds = ['npm install', 'npm run build']

[start]
    cmd = 'php artisan migrate --force --seed --class=SuperAdminSeeder && php artisan serve --host 0.0.0.0 --port $PORT'
